rm(list=ls())
library(magrittr)
library(tibble)
library(dplyr)
library(plyr)
library(tidyr)
library(stringr)
library(lubridate)
library(data.table)
library(openxlsx)
library(readxl)
library(purrr)
library(janitor)
library(scales)
library(tidyverse)
require(data.table)
require(reshape2)
require(Hmisc)
library(pivottabler)
library(skimr)
library(kableExtra)
#install.packages("pivottabler")
#install.packages('skimr')
#install.packages('kableExtra')

options(dplyr.summarise.inform = FALSE)
my_cols <- c("lead_id", "EMI_cases", "File_Type",
             "Date", "lender", "is_ldb", "is_allocated",
             "cm_pop_validation", "Final_allocation_status_before_payment", "Channel", "account_status", "amount_paid")
dump <- read.xlsx("C:\\R\\ARS_dump.xlsx",sheet = 'DATA')
tar <- read.xlsx("C:\\R\\ARS_dump.xlsx",sheet = 'month_target')
jointdf <-merge (dump, tar, by= c('lender')) %>% select("lead_id", "EMI_cases", "File_Type",
                                                             "Date", "lender", "is_ldb", "is_allocated",
                                                             "cm_pop_validation", "Final_allocation_status_before_payment", "Channel", "account_status", "amount_paid", "sku_account", "Assisted_target", "PA_STP_target", "adjustment")
colnames(jointdf)

df0 <- jointdf %>%  filter(Final_allocation_status_before_payment == 1, is_ldb == 1 & cm_pop_validation == "Accept") %>% group_by(lender, account_status) %>% dplyr::summarise('Total Collection' = sum(amount_paid, na.rm = TRUE)) %>% adorn_totals("row")

assisted_tar <- jointdf %>% group_by(sku_account) %>% dplyr::summarise('Assisted Target' = round(unique(Assisted_target, na.rm = TRUE)))
#final_df<-cbind(df0, assisted_tar)# %>% mutate ('Total M0_DTD' = sum(YES_BANK_df1+YES_BANK_df6+YES_BANK_df11), 'Total M0_MTD' = sum(YES_BANK_df2+YES_BANK_df7+YES_BANK_df12), 'Total M0_MTD_Target' = sum(YES_BANK_df3+YES_BANK_df8), 'Total M0_DRR' = as.numeric(round((`Total M0_MTD_Target` - `Total M0_MTD`)/as.numeric(Remaining_days))), 'Backlog' = round(`Total M0_MTD_Target` - `Total M0_MTD`), 'Achieved %' = percent(`Total M0_MTD` / `Total M0_MTD_Target`))
pt <- PivotTable$new()
pt$addData(lender)
pt$addColumnDataGroups("Channel")
pt$addRowDataGroups("lender")
pt$defineCalculation(calculationName="TotalCollection", summariseExpression="n()")
pt$renderPivot()
